### ISSUE TITLE
Support synchronous per host metrics

### ISSUE THREAD

**Issue by rschoene** [tud-zih-energy/lo2s#10]
It would be nice if synchronous per-host metrics could be read at the readout interval.

**Comment by tilsche** [comment]
With moving the metrics into the kernel, the readout interval is kind of irrelevant. There are no specific (userspace) events that could be associated with metric reads.

**Comment by bmario** [comment]
It does. You can only readout the metrics in user-space. During the measurement, perf_event_open only does kernel-space readouts. lo2s is only triggered, whenever the mmap buffers are full, which ideally does not happen at all during the measurement. Therefore, no wakeups where you could make a readout. What you semantically want, is an asynchronous plugin, which sets up measurement threads. The threads shall have a wake-up in regular intervals, during which you can make a readout.

**Comment by AndreasGocht** [comment]
would work as well.
