### ISSUE TITLE
Investigate missing scheduling eventsin system monitoring mode with PERF_RECORD_SWITCH

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lo2s#104]
Follow up from #79

**Comment by cvonelm** [comment]
To give a little update on the situation here
```
              PERF_RECORD_MISC_SWITCH_OUT (since Linux 4.3)
                     When a PERF_RECORD_SWITCH or PERF_RECORD_SWITCH_CPU_WIDE record is generated, this bit indicates that
                     the context switch is away from the current process (instead of into the current process).
```
This means to my understanding that SWITCH_OUT is basically a context leave
The Problem now is this:
```
                  next_prev_pid
                         The process ID of the previous (if switching in) or next (if switching out) process on the CPU.
```
This means as far as i have understood it and contrary to both common sense and how it is implemented currently, that a leave reports the next pid and an enter the last pid.

**Comment by bmario** [comment]
If I'm reading this correctly, we can basically ignore the `next_prev_pid` field and just write `pid`?

Besides the following pseduo assert:

`assert(PERF_RECORD_MISC_SWITCH_OUT || next_prev_pid == this->last_pid)`

**Comment by cvonelm** [comment]
Which pid field do you mean? The easy solution here would be using one of the next_prev_pid fields and ignoring the other. In the branch issue-104-investigate-dropped-switches I use
