### ISSUE TITLE
unknown perf record type: 14 with process monitoring

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lo2s#110]
In current master, if `lo2s` is run with simple process monitoring:

```[56899504245159][pid: 27479][tid: 140014337120000][ WARN]: unknown perf record type: 14```

These are switch records.

**Comment by cvonelm** [comment]
https://github.com/tud-zih-energy/lo2s/commit/05cc9a693e833e8821022358da84b650b3d36aa9 fixes this
