### ISSUE TITLE
Incorrect calling context

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lo2s#112]
- [ ] Use `tid` instead of `pid` for context switches
 - [ ] Store a separate ip ref map per `tid`
 - [ ] In `merge_calling_contexts`, use a parent of the thread calling context (instead of root)
 - [ ] Check if the `pid` entry can be removed from the ref map (is `tid == pid`?)
 - [ ] For efficiency, cache current ip ref map in the sample writer, but always check if the `sample->tid` equals the current tid (of the last context switch event)
 - [ ] Create small trace with sensible `otf2-print` output
 - [ ] Check if everything is shown correctly in Vampir

**Comment by cvonelm** [comment]
Furthermore fix call graph (-g). The current way we are generating the IP ref is by taking the size of the of the top level IpRefMap ignoring the children
