### ISSUE TITLE
Fix missing RAII in bfd_resolve.cpp

### ISSUE THREAD

**Issue by bmario** [tud-zih-energy/lo2s#115]
`handle_` should be a `unique_ptr` with a custom deleter which calls `bfd_close()`. This change will remove so much error spaghetti code.

Also, this line might leak, if `LineInfo::for_function()` throws. Again, use an unique_ptr with custom deleter.
https://github.com/tud-zih-energy/lo2s/blob/b69a467e108dc675e7157c5d48db858c8a160ba2/src/bfd_resolve.cpp#L149-L155

Furthermore, investigate this comment: 
https://github.com/tud-zih-energy/lo2s/blob/b69a467e108dc675e7157c5d48db858c8a160ba2/src/bfd_resolve.cpp#L140

**Comment by tilsche** [comment]
FYI https://stackoverflow.com/a/27441139/620382
