### ISSUE TITLE
Time-interval-based metric recording

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lo2s#121]
Some metrics make sense to record in idle (e.g. residency from sysfs). However, in idle, there is no useful metric-leader for recording metrics.

We should have a fallback to enable recording of metrics with intervals (like previously). Hopefully after the recent monitor refactoring, this isn't a huge deal. We need to discuss the involved monitors (share a monitor with x86_adapt?). Also configuration (confusion with `--metric-frequency`)

**Comment by cvonelm** [comment]
When are metric values written to the buffer exactly? When the metric leader runs over?

**Comment by tilsche** [comment]
In this mode the metrics are collected in userspace at the timer interrupts.

**Comment by cvonelm** [comment]
I'm sorry if I'm understanding this wrong, but is this more of a "perf side problem" (The kernel never reads metrics because whatever triggers a metric read currently doesnt trigger in idle, meaning the buffer is empty) or is this a "lo2s side problem" (metrics arrive in the buffer but we never read them because the buffer is not overflowing). Because the latter should(tm) work as readout_interval is used with metrics too.

**Comment by tilsche** [comment]
It's a *perf side problem* as you describe - but I'm afraid we have to fix it *lo2s side* unless we find an event that triggers at a constant rate even in idle.

**Comment by cvonelm** [comment]
Hmm.. `msr/tsc` as an event might be worth a try, as it uses the TSC clock as a source.

**Comment by cvonelm** [comment]
`msr/tsc` doesnt work because it doesn't support sample_freq/sample_period but their is the far more convenient `cpu-clock` which is CPU wall time. 

```./lo2s -a --standard-metrics --metric-leader cpu-clock -- sleep 10```

gives us metric, unlike using `instructions`

**Comment by tilsche** [comment]
Nice... this actually works! I thought it didn't because `perf stat -e cpu-clock -- sleep 1` didn't show any values, but I presume that's just not covered due to not being scheduled.

Then we probably just need to discuss interface & documentation.

**Comment by tilsche** [comment]
Open questions:

- Does cpu-clock support PEBS?
- Does the kernel "adjust" the perioid/count if frequency is chosen or does it compute it statically?
- Can we read the cpu-clock rate or is it well defined?

**Comment by cvonelm** [comment]
- metrics do not seem to use PEBS at all
- Statically, 😱
```c
    /*
      * Since hrtimers have a fixed rate, we can do a static freq->period
      * mapping and avoid the whole period adjust feedback stuff.
      */
     if (event->attr.freq) {
         long freq = event->attr.sample_freq;

         event->attr.sample_period = NSEC_PER_SEC / freq;
         hwc->sample_period = event->attr.sample_period;
         local64_set(&hwc->period_left, hwc->sample_period);
         hwc->last_period = hwc->sample_period;
         event->attr.freq = 0;
     }
```
-  `cpu-clock` uses hrtimer internally. hrtimers `ktime_t` is defined to be nanoseconds regardless of actual hw clock granularity
