### ISSUE TITLE
Update documentation of readout interval

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lo2s#122]
from `man lo2s`

>        -i, --readout-interval MSEC (default: 100)
>            Wake up lo2s every MSEC milliseconds to read both metric event and sampling event buffers.  Increasing this values reduces the perturbation of measurements introduced by lo2s
>            waking up to read buffers, but increases the risk of losing samples because of overflowing buffers.  Use in conjunction with --mmap-pages, --count and --metric-count to
>            minimize lo2s's overhead for your measurements.
 

from `lo2s --help`

>       -i [ --readout-interval ] MSEC (=100) Time interval between metric and 
>                                             sampling buffer readouts in 
>                                             milliseconds.

I think both are outdated and should be updated to reflect the actual things regarding readouts and watermarks.

**Comment by bmario** [comment]
Fixed for now in #126
