### ISSUE TITLE
Make readout interval configurable for watermark monitors

### ISSUE THREAD

**Issue by cvonelm** [tud-zih-energy/lo2s#127]
Currently all monitors will be read when a ```--readout-interval``` amount of time has passed. however this is often undesirable for monitors governed by perf watermark, we propose this to be configurable, with the default being that ```--readout-interval``` is only used with monitors that don't support watermarks.

For the command line interface there are two options:
- a ```--watermark-use-readout-interval``` **flag**, which, when on, will lead watermark monitors to use ```--readout-interval```
- a ```--watermark--readout-interval MSEC``` **option** which specifies a readout interval used only with watermark monitors (defaults to 0 which means that no readout interval is used, only watermarks)

**Comment by tilsche** [comment]
We keep `-i, --readout-interval` for the non-watermark monitors (x86_*) and use `-I, --perf-readout-interval` for watermark (perf sample and perf metrics).

Don't forget to update documentation.
