### ISSUE TITLE
Process Monitor adds strange things to stack

### ISSUE THREAD

**Issue by rschoene** [tud-zih-energy/lo2s#135]
I use lo2s with `lo2s -q -g bash`, then start 2 processes (bt.W.x and sp.A.x), each with 4 threads. The main thread of each process has bash at the bottom of its stack, then some unknown, then libGOMP, then the executed functions. If I see it correctly, all below libGOMP is broken.

More at `taurus:/trcdata/tracefiles/rschoene/lo2s_issue_135.tgz`

(bash: orange, broken: light green, OMP: brown, sp.A.x: light blue)
![lo2s_135](https://user-images.githubusercontent.com/9930030/68671609-fa699480-054f-11ea-8937-540389a49025.png)

**Comment by cvonelm** [comment]
Which version of lo2s did you use? We recently found and fixed a regression in https://github.com/tud-zih-energy/lo2s/commit/8c776f8f78a3344dad6e2fc7f97595f0ace14326 which broke name resolution

**Comment by rschoene** [comment]
lo2s v1.2.2-18-g8c776f8

**Comment by rschoene** [comment]
Unfortunately, this was not fixed in #140. With a fresh checkout v1.2.2-23-gde0bc86(), I can still see bash sitting on the lowest level for an sp.A.x process.
