### ISSUE TITLE
Support metric event name translation via libpfm4

### ISSUE THREAD

**Issue by rschoene** [tud-zih-energy/lo2s#139]
Support more event types via libpfm4, which can give you the raw event code for a given human readable performance event description. libpfm4 seems to be developed at sourceforge: [https://sourceforge.net/projects/perfmon2/](https://sourceforge.net/projects/perfmon2/)
The metrics should be labeled with their human readable name AND the underlying raw event for reproducibility reasons.

**Comment by cvonelm** [comment]
Implemented in 92f68a89f2aa8bb40f6725ee7e1f13001b11d6df
