### ISSUE TITLE
Remove boost dependency

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lo2s#147]
We don't really need boost, but it gives us some trouble and dependency.

- [x] `format` ⇨ fmtlib with a path to C++20
- [x] `filesystem` ⇨ C++17
- [x] `algorithm/string` (`split`, `startswith`, `replace_all`) ⇨ nitro? (C++20)
- [x] `program_options` ⇨ nitro

**Comment by cvonelm** [comment]
For `algorithm/string`: The way to do this, atleast in my mind, is to reimplement the needed functions in plain C++, however should the code for that live inside lo2s or nitro?

**Comment by tilsche** [comment]
> should the code for that live inside lo2s or nitro?

Sounds like nitro to me. @bmario ?

**Comment by bmario** [comment]
Fixed with #171
