### ISSUE TITLE
Introduce """safe""" metric read out option

### ISSUE THREAD

**Issue by cvonelm** [tud-zih-energy/lo2s#158]
The way lo2s reads out metrics right now is very effective, but does not work for all
metrics, namely the MPERF and APERF metrics.

To still be able to record those outliers we've decided to introduce an option for reading out metrics in the most plain, but most ineffective way.

- introduce a new interval based monitor
- introduce a --safe-metric and --safe-readout-interval (Better names always welcome)
- introduce short cuts for --aperf and --mperf

**Comment by cvonelm** [comment]
@bmario @tilsche Some minor issues that need to be discussed:

If the event is specified as both a normal and a safe event (e.g. `lo2s -e cpu-cycles --safe-metric-event cpu-cycles`) the metric event is only displayed once in Vampir. Should we:

1. Name events differently by their reading mode (`cpu-cycles (group)`and  `cpu-cycles (safe)` instead of just `cpu-cycles`)
2. Disallowing the use of one event in both and exeting with a warning 
3. Printing a warning and only using it in safe metric mode (`cpu-cycles specified as both normal and safe event, only using it as a safe event`

Secondly. do we want time_enabled and time_running for safe metrics too

and if yes do we want them 

1. aggregated (`time_enabled (safe)` is the average of all safe events `time_enabled` field)
2. per event ('time_enabled (cpu-cycles,safe)`)

**Comment by tilsche** [comment]
I think Option 3) is best unless we would want that for debugging and verfication of lo2s itself... Then we would go with a different name *only if both are specified*.

I don't think we need `time_enabled` and `time_running` this much to warrant the extra complexity and trace size.

**Comment by cvonelm** [comment]
- Rename this functionality from misleading "safe metrics" to less misleading "userspace metrics".
- We do not use the same readout interval option for normal and userspace metrics, because userspace metrics are far more slow than normal metrics. If we used one option for both the minimal achievable readout interval would drastically increase for normal metrics.
