### ISSUE TITLE
FindStdFilesystem.cmake fails on older versions

### ISSUE THREAD

**Issue by cvonelm** [tud-zih-energy/lo2s#160]
Our new FindStdFilesystem script uses features that are not available in older versions of cmake (like 3.10, which is installed on the ZIH test systems).

This is probably caused by two things:

We don't set required compiler options like `--std=c++17` or `-lstdc++fs` in the `check_cxx_source_compiles` check. Later versions of cmake seem to set those implicitly, so the check works without those there.

Setting target_compile_features for IMPORTED targets (like std::filesystem in our case) is only possible since 3.11 [1][2]

Two options:

1. Rework the `check_cxx_source_compiles` (trivial) and `target_compile_features` (no clue) stuff to work with older cmakes
2. Bump the cmake version requirement to 3.11 

[1]https://cmake.org/cmake/help/v3.10/command/target_compile_features.html
[2]https://cmake.org/cmake/help/v3.11/command/target_compile_features.html

**Comment by bmario** [comment]
Bump to 3.11 and use the installed module version.
