### ISSUE TITLE
process monitoring: no association to process name

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lo2s#180]
e.g. if I run FIRESTARTER, the threads are shown as `LoadWorker (tid)`, with function group `LoadWorker`. There should be some way to associate them with the actual process name `FIRESTARTER`.

The current suggestion is to have the function group be `Process Name (pid)`.

**Comment by bmario** [comment]
Note, Vampir shows it as a "function group", but it should be the `location_group` definition.
