### ISSUE TITLE
Add a replacement for {PID} in the lo2s trace output name

### ISSUE THREAD

**Issue by bmario** [tud-zih-energy/lo2s#181]
Running lo2s with this command `lo2s -o lo2s_trace_{PID} -- <app>` should create an output trace with the PID of the root process.
Similarly, when attaching to a process using `lo2s -o lo2s_trace_{PID} -p <pid>`, the output trace should contain the PID of the attached process.

Obviously, in system-monitoring mode, the PID does not make sense, thus lo2s should complain about it and exit.

From a technical standpoint, this is complicated, because the PID is only known once the observed process was spawned, but at that point down the initialization, the otf2 trace was already created. Thus, the name is already determined before the time the PID is knowable.

**Comment by tilsche** [comment]
We can't do this directly, so this would only work with folder-renaming as workaround there are things that can go wrong there. It seems not worth the effort.
