### ISSUE TITLE
Debug build is broken

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lo2s#195]
Plenty of bad code in `assert`s.

Do we do have a debug build in our CI?

**Comment by cvonelm** [comment]
I've added the `static_cast`s required for clang to stop complaining about the value changing because of the the implicit cast to double in https://github.com/tud-zih-energy/otf2xx/pull/66

However otf2xx's CI seems to be a little bit broken right now

**Comment by cvonelm** [comment]
As the last commit fixed the asserts, I'm closing this.
