### ISSUE TITLE
Support older Linux versions

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lo2s#2]
Currently needs 4.1 (data_offset / data_size). Need to figure out if there other compatibility issues (time_enabled / time_active bug).

Need this for taurus.

**Comment by bmario** [comment]
Should be fixed.

**Comment by tilsche** [comment]
Not sure about time_enabled / time_active for multiplexing? We don't necessarily need multiplexing, but maybe mark as known issue that multiplexing is broken on old Linux versions or so?
