### ISSUE TITLE
cmake Binutils_USE_STATIC_LIBS=OFF not respected when set via commandline

### ISSUE THREAD

**Issue by s9105947** [tud-zih-energy/lo2s#210]
Dear maintainers,

during an automated build my settings given to cmake got ignored.

### Steps to Reproduce
1. clone lo2s into a directory, change there
2. `mkdir build && cd build`
3. ~~`cmake Binutils_USE_STATIC_LIBS=OFF ..`~~
   EDIT: use `cmake -DBinutils_USE_STATIC_LIBS=OFF ..`
4. check content of `Binutils_USE_STATIC_LIBS`, e.g. `cmake -L . | grep Binutils_USE_STATIC_LIBS` (or just `ccmake` etc.)

### Expected Behavior
The cmake variable `Binutils_USE_STATIC_LIBS` is set to `OFF`.

### Actual Behavior
The cmake variable `Binutils_USE_STATIC_LIBS` is set to `ON`, in my case the build fails because of that (static libraries are not available).

### Additional Notes
As far as I can tell this is caused by a call to `IfUpdatedUnsetAll` inside of `cmake/FindBinutils.cmake`.
This seems to be activated prematurely.

**Comment by cvonelm** [comment]
Are you sure you are invoking cmake right?

With

```bash
[cvonelm@roronoa build]$ cmake -DBinutils_USE_STATIC_LIBS=OFF ..
[...]
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cvonelm/projects/lo2s/build
[cvonelm@roronoa build]$ cmake -L . | grep Binutils_USE_STATIC_LIBS
Binutils_USE_STATIC_LIBS:BOOL=OFF
```

**Comment by s9105947** [comment]
1. The above cmake invocation was incorrect, `-D` was missing. The correct call is: `cmake -DBinutils_USE_STATIC_LIBS=OFF ..`
2. The error still persist in my test setups

I have confirmed it on 2 separate systems.

Note that I am using a fresh (empty) `build` directory; invoking cmake to set the variable works the second time.

> btw the workaround is to use `-Dlo2s_USE_STATIC_LIBS=OFF`, but explicitly setting `Binutils_USE_STATIC_LIBS` is still ignored.

Somehow the (unset) variable `lo2s_USE_STATIC_LIBS` (defaults to `ON`) seems to take precedence over the explicitly given `Binutils_USE_STATIC_LIBS`
