### ISSUE TITLE
Wrong calculation for scaled counter values in legacy code path

### ISSUE THREAD

**Issue by phijor** [tud-zih-energy/lo2s#22]
I'm not sure if this supposed to be that way, but it seems like the line [here](https://github.com/tud-zih-energy/lo2s/blob/04c99f91b8f402ccef5fca09ef270e044e16a324/include/lo2s/metric/perf_counter.hpp#L97) should instead of
```
return (static_cast<double>(value) / running) * value;
```
be
```
return (static_cast<double>(enabled) / running) * value;
```

What do you think?

**Comment by tilsche** [comment]
Yes, can you just change it please?
Just wondering, did you see that with sharp eyes or have you encountered trouble during testing?

**Comment by phijor** [comment]
My search-and-replace highlighted `value` two time on this line and I thought "wait, that doesn't look right". So sharp eyes I guess? :grimacing:

**Comment by hackenbe** [comment]
👏

**Comment by tilsche** [comment]
thought it was fixed, but it's still in a branch. oops.

**Comment by bmario** [comment]
This will be part of #26
