### ISSUE TITLE
LO2S::STARTING_TIME has no timezone identifier and is not easily parsible

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lo2s#244]
ISO 8601 all the way!

Bonus points for sub-seconds.

**Comment by tilsche** [comment]
Fine point, but we also need to write this in lo2s (it was recently added).

I am using that data to get energy information from existing un-instrumented traces... So it's not for Vampir in that case. That's also why I'd prefer sub-seconds, which the `realtimeTimestamp` doesn't support :-(

**Comment by bmario** [comment]
There's no sub-second format specifier though. https://fmt.dev/latest/syntax.html#chrono-specs This is, because std::tm isn't sub-second aware.

Can we rewrite in a usable language yet?
