### ISSUE TITLE
cpumask support for PMU events

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lo2s#259]
Consider `uncore_clock/clockticks/` on alderlake. Apparently this event cannot be recorded on a pid, but only on a cpu.
So currently, with `lo2s` it can only be recorded with `-a --userspace-metric-event uncore_clock/clockticks/`. At least `-a` should not be necessary, we should automatically chose the right PID/CPU scope.

That should be based on `/sys/bus/event_source/devices/*/cpumask` (since Linux 3.7)

> The cpumask file contains a comma-separated list of integers that indicate a representative CPU number for each socket (package) on the motherboard.  This is needed when setting up uncore or northbridge events, as those PMUs present socket-wide events.

See also related `perf` [commit](https://lore.kernel.org/lkml/20220422162402.147958-20-adrian.hunter@intel.com/).

**Comment by cvonelm** [comment]
This is in general a problem in two parts:

- [ ]  lo2s does not respect the `cpumask` field at all 
- [ ] We want to mix process mode measurements with system mode measurements.

I personally dislike any solution for the latter that implicitly does stuff such as detecting the `cpumask` field and then setting up the metric per-CPU. I think there should be some explicit syntax for that.
