### ISSUE TITLE
Overhead introspection

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lo2s#28]
* [ ] Write event records for perf mmap buffer flushes
 * [x] After execution, print number of wakeups if not quiet.

**Comment by bmario** [comment]
Print the number of wakeups is part of #31

**Comment by tilsche** [comment]
Writing records is impossible due to monotony.
We discussed writing an asynchronous metric instead, but that would add significant complexity.
We already have `time_running` to get a feeling about any scheduling interruption, not just by monitoring.
