### ISSUE TITLE
Use perf list syntax for tracepoint events

### ISSUE THREAD

**Issue by rschoene** [tud-zih-energy/lo2s#30]
Currently, tracepoint events are specified with slashes e.g., `exceptions/page_fault_kernel`, perf list names them with colons, e.g., `exceptions:page_fault_kernel`.

I'd vote for the perf list style. Any other opinions?
 @tilsche @bmario @AndreasGocht @phijor @cvonelm 

(Vote yes/no/0, everyone has one vote, as soon as there's a majority for "yes" the issue will be assigned, as soon as there's a majority for "no", the issue will be closed, 0 is for abstention)

**Comment by rschoene** [comment]
+

**Comment by tilsche** [comment]
yes, make that the documented way, but simply support both for the time being. Shouldn't be any issue splitting by either character.

**Comment by bmario** [comment]
yes
