### ISSUE TITLE
Update ClangFormat options

### ISSUE THREAD

**Issue by bmario** [tud-zih-energy/lo2s#304]
Things I've been looking for anyways:

- [InsertNewlineAtEOF](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#insertnewlineateof) to true
- [keepemptylinesatthestartofblocks](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#keepemptylinesatthestartofblocks) to false
- [EmptyLineBeforeAccessModifier](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#emptylinebeforeaccessmodifier) to always
- [SeparateDefinitionBlocks](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#separatedefinitionblocks) to always

**Comment by tilsche** [comment]
Yes, please.
