### ISSUE TITLE
add sampling source as counter

### ISSUE THREAD

**Issue by rschoene** [tud-zih-energy/lo2s#32]
When specifying a different sampling event (e.g., via `-e cpu-cycles`), the event is not recorded as a counter. Please add it.

**Comment by phijor** [comment]
I would like to address this as soon as PR #26 is merged. It has the infrastructure in place to collect counters in a central place, which makes this an easy change.

**Comment by rschoene** [comment]
I would have preferred (1). Since this is "problematic", it should not be implemented.
