### ISSUE TITLE
Score-P independend environment variables for metric plugins

### ISSUE THREAD

**Issue by AndreasGocht** [tud-zih-energy/lo2s#37]
Currently lo2s reuses the `SCOREP_METRIC_PLUGINS` to add metric plugins. It would be good if there is an Score-P independent environment variable to add metric plugins, e.g. a `LO2S_METRIC_PLUGINS` variable.

This would avoid confusion with Score-P metric plugins as LO2S has a slightly different interface (synchronous plug ins are not handled as far as I know) and unintended side effects are avoided if Score-P is traced.

Best,

Andreas

**Comment by bmario** [comment]
Well, the original thought was, that we could reuse the Score-P metric plugins and especially don't have to change the modules. But going forward it might be a good idea to use a lo2s specific variable and just fix the modules instead.

**Comment by tilsche** [comment]
If you want to trace a Score-P program with lo2s, I suggest using a wrapper script to make sure each sees the right variable for him.

The compatibility is really nice with dozens of modules on many systems... `lo2s` should handle compatibility issues gracefully - if not, then that is a bug.

**Comment by tilsche** [comment]
Please make a PR that reads `LO2S_METRIC_PLUGINS` if it is not defined, it falls back to `SCOREP_METRIC_PLUGINS`.
