### ISSUE TITLE
Remove default metric channels

### ISSUE THREAD

**Issue by bmario** [tud-zih-energy/lo2s#47]
I think we shouldn't use any default metrics for various reasons:

- They are only there because of legacy reasons and laziness 
- There is not this one apparent set of default metrics
- They introduce overhead by default without the possibility to disable them
- We haven't documented, which metrics are added by default
- Passing one additional metric suddenly removes all default metrics, which is a surprising behavior

**Comment by cvonelm** [comment]
Does this also affect the default metric leader ?

**Comment by bmario** [comment]
No, metric leader should have a default, however this still applies: #48
