### ISSUE TITLE
Unexpected exit in -a mode if /sys/kernel/debug is read-only

### ISSUE THREAD

**Issue by phijor** [tud-zih-energy/lo2s#52]
Run `lo2s`:
```
$ ./lo2s -a -- true
[1521149802129234474][pid: 25222][tid: 140210198903680][ERROR]: Aborting: basic_ios::clear: iostream error
```

I traced this down to the constructor of `lo2s::perf::tracepoint::EventFormat` throwing [here](https://github.com/tud-zih-energy/lo2s/blob/7522d2f5cf2d4395fd9b7266541c76d310b1fff9/src/perf/tracepoint/switch_writer.cpp#L42), potentially [here](https://github.com/tud-zih-energy/lo2s/blob/7522d2f5cf2d4395fd9b7266541c76d310b1fff9/src/perf/tracepoint/exit_reader.cpp#L37) too.

What would be the correct behavior here? Rethrow a meaningful exception instead of `std::ios_base::failure`? Log and exit? Check `lo2s::perf::tracepoint::get_sched_switch_event()` before starting the trace?

**Comment by bmario** [comment]
0. Rant about iostream exceptions
1. rethrow meaningful exception [here](https://github.com/tud-zih-energy/lo2s/blob/master/src/perf/tracepoint/format.cpp#L48)
2. Check lo2s::perf::tracepoint::get_sched_switch_event() before starting the trace
3. Rant again in commit message about iostream exceptions

But please finish the other two PRs first. ;)
