### ISSUE TITLE
Add uname information to otf2

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lo2s#56]
When tracing lots of different kernel versions it would be nice to have some uname information available in the trace.

I suggest to include several `uname` outputs, most importantly `uname -r` and `uname -v`, others won't hurt.

I suggest to use `archive_.set_property("LO2S::...")` as this is easily accessible in Vampir. It is a bit of "creative use", technically it should probably be some global definition like a system tree node property. But that would be much harder to show in Vampir.

**Comment by tilsche** [comment]
Sure, we can do that *in addition*.

**Comment by phijor** [comment]
350982c has a WIP implementation. Is this the direction you want this to be going? TBH I'm not sure if we need the `system_tree_node_properties_`  container; are there any other `LO2S::...` properties we might want to add to the trace?

**Comment by tilsche** [comment]
I think we should have the container for consistency anyway.

The WIP is missing `archive_.set_property`.

Looking at the interface, I'd suggest to put all the struct members as separate properties.

**Comment by phijor** [comment]
Doesn't [this](https://github.com/tud-zih-energy/lo2s/commit/350982c05daa82b2b144f2d48ec8d0edbc0950ec#diff-1080ec2e46093f404fcf651ae4336d2aR213) take care of writing the properties to the archive? I'm not quite sure I understand what the difference is between this and `archive_.set_property`. But then again my knowledge of the `OTF2_`-interface is only slowly getting better.

Nonetheless, :+1: from me for putting all the information of `struct utsname` into separate properties.

**Comment by tilsche** [comment]
> Doesn't this take care of writing the properties to the archive? I'm not quite sure I understand what the difference is between this and archive_.set_property. But then again my knowledge of the OTF2_-interface is only slowly getting better.

No, the system tree node properties (which those are definitions referring to a specific system tree node) are different and redundant to the archive properties (which aren't definitions and are global). The reason I want the latter are of practical nature - they are easier to show with Vampir.

**Comment by phijor** [comment]
Ahh, I see.

Maybe c241766  is the way to go. Each member `struct ::utsname::<member>` is written to the archive<sup>(using `archive_.set_property()`)</sup> as `LO2S::UNAME_<member>`. Some of the code could be de-duplicated incurring some run-time overhead, but I think that'd be okay.

Final result looks like this in Vampir:

![2018-04-10-161147_515x156_escrotum](https://user-images.githubusercontent.com/10487782/38563136-6dd6d2ae-3cdc-11e8-8050-dcf54bbd55ae.png)

`utsname::domainname` is not written right now; `uname(2)` says it's only available if `_GNU_SOURCE` is defined.
