### ISSUE TITLE
Improve error message when x86_energy isn't installed

### ISSUE THREAD

**Issue by phijor** [tud-zih-energy/lo2s#69]
Starting with d41121e, trying to generate the build files with `cmake ` yields the following message:

```
CMake Warning at CMakeLists.txt:101 (find_package):
  By not providing "Findx86_energy.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "x86_energy", but CMake did not find one.

  Could not find a package configuration file provided by "x86_energy"
  (requested version 2.0) with any of the following names:

    x86_energyConfig.cmake
    x86_energy-config.cmake

  Add the installation prefix of "x86_energy" to CMAKE_PREFIX_PATH or set
  "x86_energy_DIR" to a directory containing one of the above files.  If
  "x86_energy" provides a separate development package or SDK, be sure it has
  been installed.
```

There is no file `cmake/Findx86_energy.cmake`, did someone forget to add that to a commit  or am I missing something?

**Comment by bmario** [comment]
That is the expected behavior. There is no find script, because find scripts are shit. The way to go is to provide a `x86_energyConfig.cmake` file, which (x86_energy/v_2)[https://github.com/tud-zih-energy/x86_energy/tree/v_2] does. Having said that the default message from CMake is just garbage

**Comment by bmario** [comment]
And yes, you missed the second part of the message:


> Add the installation prefix of "x86_energy" to CMAKE_PREFIX_PATH or set "x86_energy_DIR" to a directory containing one of the above files.  If  "x86_energy" provides a separate development package or SDK, be sure it has  been installed.

**Comment by bmario** [comment]
Turns out the correct thing to do is put find_package into CONFIG mode. See d9a95afd76d47090d7baec5cce555ef155e39c19
