### ISSUE TITLE
Better time synchronization

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lo2s#7]
- [x] Make use of use_clockid (since 4.1) to set a good clock for perf
- [x] Add option to list all available clocks
- [ ] Use time_shift, time_mult, time_offset (since forever) // time_zero (since 3.12) to make time conversion

**Comment by bmario** [comment]
In Perf record this options are called:  -k, --clockid

**Comment by bmario** [comment]
Set perf clock also in `lo2s::perf::sample::Reader<T>::init(...)` and `lo2s::perf::tracepoint::Reader<T>::init(...)`

**Comment by phijor** [comment]
So after fiddling probably way to long with this: `CLOCK_MONOTONIC` seems to be the clock we want. Here are some offsets between `perf_time` and `local_time` as reported by `lo2s::perf::time::Converter`: 

|clock|offset (ns)|
|-|-:|
|`CLOCK_MONOTONIC`|-6563|
|`CLOCK_MONOTONIC_RAW`|391393036|
|none|1826627983|

(only these two seem to work for me, `CLOCK_(REALTIME|BOOTTIME|TAI)` fail with `EINVAL`).

**Comment by phijor** [comment]
TODO:
- [ ] warn if `-k` is specified but lo2s was compiled without support for it

**Comment by bmario** [comment]
Bullet point one fixed with 5a2239ff41007577f9ef6bf74b607e8b5f45e02a

**Comment by tilsche** [comment]
Masterplan:

- small chrono::clock wrapper around clock_gettime
- Use same clockid_t for the local timer as we use for perf (if available)
- Default to `CLOCK_MONOTONIC_RAW`
- If a perf clock is set, do a time synchronization anyway and check if offset is within a threshold (-100 us, 0). Warn if not. Always use `offset=0`.
- If perf clockid is not available we can still offer the user to chose a local_clock.

**Comment by bmario** [comment]
The clock wrapper may should be part of Nitro

And what about older kernels?

**Comment by tilsche** [comment]
> And what about older kernels?

Older kernels do the same time synchronization as currently. But they can use the selected timer as local timer just as well.

**Comment by phijor** [comment]
Some news:

- using the same clock for `lo2s` and `perf` results in a consistent offset (~6us on my machine) for clocks `MONOTONIC` and `MONOTONIC_RAW`
- calling `Clock::now()` after `perf` has received the `HW_BREAKPOINT` interrupt and execution resumed in `lo2s` yields another relatively consistent offset (~6us)

**Comment by bmario** [comment]
The only open thing here is:
>  Use time_shift, time_mult, time_offset (since forever) // time_zero (since 3.12) to make time conversion

But I think that is obsolete or isn't it?

**Comment by tilsche** [comment]
> But I think that is obsolete or isn't it?

It kinda isn't as time conversion is still done. If `clockid` is specified, it is still used as a sanity check. Maybe the `time_(shift,mult,offset,zero)` can help with that, but I we don't want to spend too much energy on old kernels.
