### ISSUE TITLE
Look into PERF_RECORD_SWITCH

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lo2s#79]
There are relatively new (Linux 4.3) records which seem to provide the same information as the  `sched_switch` tracepoint.

> This functionality is in addition to tracepoint and software events for measuring context switches.  The advantage of this method is that it **will full information even with strict `perf_event_paranoid` settings**.

We should also look into that if it gives other advantages, e.g. less overhead than tracepoints.

**Comment by bmario** [comment]
Would this allow a system-mode with user privileges? Because Holger is asking for this. (but for Taurus... 💀)

**Comment by tilsche** [comment]
As I understand it, this allows non-root system-mode monitoring with `perf_event_paranoid < 1` without having access to `/sys/kernel/debug`

**Comment by cvonelm** [comment]
Switch events now work without having access to /sys/kernel/debug. The only remaining place where we need access to tracepoints in system mode is reading the process comms, which currently works as follows:
1. Read comms of processes that have exited while we are still measuring from a tracepoint (happens in src/perf/tracepoint/exit_reader.cpp)
2. After we have finished measuring read the comms of processes which are still running via /proc/[pid]/task/[tid]/cmdline (happens in read_all_tid_exe())

PERF_RECORD_EXIT does not seem to be a drop-in replacement here, as we can't get the process comm from this event as far as I have understood it.

I would propose a solution based on PERF_RECORD_COMM events:

1. Prefill the map of process comms from /proc/[pid]/task/[tid]/cmdline
2. Update the initial map continuously by reading PERF_RECORD_COMM events globally

**Comment by tilsche** [comment]
Yes, with proper `PERF_RECORD_COMM` support, we shouldn't need the `ExitReader` any longer. However,  I'm not sure #84 will already do the trick for this use-case.
