### ISSUE TITLE
--no-kernel isnt working currently

### ISSUE THREAD

**Issue by cvonelm** [tud-zih-energy/lo2s#83]
Due to event_is_openable in src/perf/event_provider.cpp always assuming perf_attr->exclude_kernel = 0 tracing is not possible currently with --no-kernel.

Possible solutions are:
* Fail and print an error message if the event isn't openable with the current exclude_kernel value.
* Setting exclude_kernel to 1 in the config if we fail to open it with 0 and print a warning message about kernel_paranoid being too strict (In line with what we do in the perf/sample/reader.cpp if kernel_paranoid is to strict for the current exclude_kernel value)

**Comment by tilsche** [comment]
I understand that `--no-kernel` and `paranoid=2` doesn't work - even though it should. But `--no-kernel` with `paranoid<=2` currently works if you just don't want it in your trace, right?

I agree with the second solution.

**Comment by cvonelm** [comment]
Yeah, the event_is_openable always checks with --kernel thus failing if paranoid= 2
