### ISSUE TITLE
Sampling in global view

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lo2s#9]
The holy grail

- [x] Record per-cpu call stack samples into the global view (-a)
- [ ] Create a thread-view trace from the global recordings optional, both or through Vampir

**Comment by cvonelm** [comment]
Continuing on what we spoke about last Wednesday I got an idea which might be worth considering. What about a mmap monitor, which would independently read the mmap events for everything and let the sample reader just read the samples, which would  eliminate most of cross thread dependencies, and would separate those 2 concerns, without the need of caching. Only downside would be slightly more overhead in process mode, as we have to filter all mmap events to only read those relevant to the pids we are sampling

**Comment by tilsche** [comment]
IF you sample all mmaps for all processes, this would also (unnecessarily) increase the requirements for `perf_event_paranoid` in process mode.

I am also concerned about extra overhead, e.g. more threads that possibly need to wakeup, more open perf structures in the kernel, more use of limited mmap pages.

**Comment by bmario** [comment]
holy grail added in 411378f9fa7218bba0366752e41c9e18799c4925

@tilsche What is this thread-view thing about?

**Comment by tilsche** [comment]
As discussed today in the big meeting, we will not really have a per-thread-view for now. Maybe some time in post-processing.
