### ISSUE TITLE
DSO canoical path resolution seems broken

### ISSUE THREAD

**Issue by phijor** [tud-zih-energy/lo2s#90]
Since ec7c40a, lo2s fails to correctly resolve the canonical path of a DSO:
```
[SNIP...]
[12665142099548][pid: 1914][tid: 140494441465600][DEBUG]: dso is not a valid file: could not resolve to canonical path: /usr/bin^A
[SNIP...]
```
note the random binary garbage byte `^A` at the end, this is not consistent between runs.

Will investigate further when there's time for that, just letting you know.

@cvonelm maybe you can take a look why this is happening?

**Comment by bmario** [comment]
Fixed in the calling context branch

**Comment by bmario** [comment]
To be precise: c1e2ca0662bb50ce283a2391ec45b7e484935cd9
